### PR TITLE
Autotools (add builtin endian support)

### PR DESCRIPTION
**Pull request by 65278**
Since Ildus prototyped support for portable/builtin endian swapping (using cmake), I've ported his ideas to autotools.
The old makefile based system remains supported.

To test: ```autoreconf -fi; ./configure && make```

### CODE REVIEW

**Comment by za-arthur** [comment]
Sadly, Ubuntu has old libconfig 1.5:
```
libconfig needs to be at least version 1.7
```

**Comment by 65278** [comment]
I'll try an ubuntu build and see if the test works with ubuntu 20.04 (I guess?)

**Comment by 65278** [comment]
Ubuntu and debian should be the same in this regard. If I'm doing autotools (and I am), we may as well dynamically find headers ;)

**Comment by za-arthur** [comment]
Thank you. It compiles now, tests pass. There are several warnings, which might be important or not.

```
In file included from ../src/exports.c:16:
../src/utils/endian.h:69: warning: "htobe32" redefined
   69 | #define htobe32(x)      bswap32(x)
      | 
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:176,
                 from /usr/include/stdlib.h:394,
                 from ../src/exports.c:5:
/usr/include/endian.h:44: note: this is the location of the previous definition
   44 | #  define htobe32(x) __bswap_32 (x)
      | 
In file included from ../src/exports.c:16:
../src/utils/endian.h:70: warning: "htobe64" redefined
   70 | #define htobe64(x)      bswap64(x)
      | 
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:176,
                 from /usr/include/stdlib.h:394,
                 from ../src/exports.c:5:
/usr/include/endian.h:49: note: this is the location of the previous definition
   49 | #  define htobe64(x) __bswap_64 (x)
```

Probably the PR replaces functions deliberately, therefore this warning might not be important enough.

```
../src/postgres.c: In function ‘_cpycmd’:
../src/postgres.c:72:13: warning: a label can only be part of a statement and a declaration is not a statement [-Wpedantic]
   72 |             __attribute__((fallthrough));
```

Looks like this is covered by https://github.com/adjust/schaufel/pull/100

```
dummy_consumer_test.c: In function ‘main’:
dummy_consumer_test.c:22:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   22 |     if (string != NULL)
      |     ^~
dummy_consumer_test.c:24:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
   24 |         printf("%s\n", string);
```

Here we could add curly brackets. But this doesn't look like a target of this PR.

**Comment by 65278** [comment]
The problem with redefining htobe{32,64} is a glibc specific problem: you can not include sys/types.h without including endian.h unless you forego XOPEN_SOURCE and BSD_SOURCE.
That said, I'll fix that.
 I'll make a new PR for dummy_consumer_test.c, as I don't like PR scope creep.

**Pull request merged**
