### PR TITLE
Json exports

### PR DESCRIPTION
**Pull request by 65278**
This branch provides the possibility to dereference json data and export to a postgres table.

The copy format is binary to simplify working with strings and provide more insert performance. The exporter depends on the new config format, as it needs rfc6901 json pointers to do its work and those don't fit on the c ommandline.

### CODE REVIEW

**Comment by zilder** [comment]
`calloc`'s return value is not always checked for `NULL`:

* `_leapyear()`
* `_json_to_pqtimestamp()` 
```
    current->result = calloc(1,9);
    memcpy(current->result, &epoch, 8);
```
* `_thread_validate()`: allocation of `buf`. Actually it looks like static allocation would be enough here:
```
   char buf[1024];
```
* It's not the part of this patch, but might be fixed as well:
    * `redis_producer_init()`
    * `redis_consumer_init()`
    * `redis_consumer_handle_reply()`
    * `dummy_consumer_consume()`

Also there are inconsistent error messages for allocations. Sometimes it's "allocate failed", sometimes "Failed to calloc". I suggest we add a macro for allocations that would incorporate check for NULL's and throwing an error.

**Comment by zilder** [comment]
In `_leapyear()` you use sizeof pointer to an int, not the sizeof int, which leads to allocating (on 64bit systems) twice the size of memory actually needed. Should be:
```
    uint32_t *l = calloc(2048, sizeof(uint32_t));
```

**Comment by zilder** [comment]
`_needles()` and `_needles_alloc()` should be annotated as static because they aren't used outside the module.

**Comment by zilder** [comment]
In `exports.c` there is no need for the second typedef for `struct Needles`. So something like this should do it:
```
typedef struct Needles *Needles;
struct Needles {
    char           *jpointer;
    ...
    uint32_t       *leapyear;
};
```
Personally I think that using linked list here is not justified and it takes extra effort to understand and maintain the code. As I understand, there is no need to dynamically add or remove items as we know the number of items from the beginning and it doesn't change. I would prefer to have separate structure for single needle item and we already have an upper level container (`struct Internal`) to store and address them.

Then `format` and `free` function pointers could be a part of `pg_type` struct, and `Needle` could have a pointer (or index) to its `pg_type` item. Ofc it's only my personal speculations.

For `leapyear` it think we could have a global variable and initialize it somewhere in `main`. Currently it is calculated for every needle (including `text` ones which don't use it).

**Comment by zilder** [comment]
We already talked a bit about `array_free`. I think the caller should be responsible for setting pointer to an array to `NULL` after freeing it, not `array_free` itself. I think we should keep standard C semantics.
```
// caller
array_free(replica);
replica = NULL;
```
And `array_free` should not accept pointer to a pointer to `struct Array` as it does now, but just pointer to `struct Array` (or just `Array` because of typedef) as other `array_*` functions:
```
void
array_free(Array array)
```

**Comment by zilder** [comment]
Need to add
```
config_destroy(&config);
```
to `t/config_merge_test.c` and `t/file_consumer_test.c`. Otherwise `valgrind` reports memleaks and makes it difficult to see if there are actual memleaks.

**Comment by zilder** [comment]
In `validator.h` there is no need to include the whole bunch of stuff. Just
```
#include <libconfig.h>
#include <stdbool.h>
```
is enough. Same as with `struct Needles` only one typedef will do.

**Comment by 65278** [comment]
> Personally I think that using linked list here is not justified and it takes extra effort to understand and maintain the code. As I understand, there is no need to dynamically add or remove items as we know the number of items from the beginning and it doesn't change. I would prefer to have separate structure for single needle item and we already have an upper level container (`struct Internal`) to store and address them.

I did not want to carry an iterator/number of elements around everywhere while prototyping. I can array-ify the code (since I can't avoid having a count altogether). If I don't like the result the list stays, though.
 
> For `leapyear` it think we could have a global variable and initialize it somewhere in `main`. Currently it is calculated for every needle (including `text` ones which don't use it).
That wtf is due to lazyness. I wanted one codepath with as little cases as possible. I'll see whether I can fix it with elegance.

**Comment by zilder** [comment]
`get_thread_count` - same as in `_thread_validate`, `buf` may be allocated statically.

**Comment by zilder** [comment]
Btw I started to refactor all the headers, so you don't need to. Will create a new PR after this one gets merged.

**Comment by zilder** [comment]
One stylistic note if i may. I noticed that you use `{` mostly on the same line with the statements (`if`, `while` etc) while original Robert's code has them on separate lines. Sometimes you mix them:
```c
    if (PQstatus(m->conn_master) != CONNECTION_OK)
    {
        logger_log("%s %d: %s", __FILE__, __LINE__, PQerrorMessage(m->conn_master));
        abort();
    }

    if (pthread_mutex_init(&m->commit_mutex, NULL) != 0) {
        logger_log("%s %d: unable to create mutex", __FILE__, __LINE__ );
        abort();
    }
```

**Pull request merged**
